### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by xmha97** [bitstuffing/campdf#1]
How I can download APK?

**Comment by bitstuffing** [comment]
> How I can download APK?

Hi, there is no release at this moment, like I've indicated in the Readme the state is "in development". So... I suggest you take into account github actions:

https://github.com/bitstuffing/campdf/actions

There you're able to download two apks for each commit (zipped). The first is the currently normal architecture, the last one is the universal for all architectures (it's bigger):

campdf-arm64-v8a-XXX-debug.apk 
campdf-universal-XXX-debug.apk 

So... answering to you, you can download from github actions the final apk if you don't want to compile it in your local machine.

Greetings!

**Comment by xmha97** [comment]
Ok, thanks for your reply.
