### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by xmha97** [bitstuffing/campdf#2]
Please add the dark mode to this app.

**Comment by bitstuffing** [comment]
Well, it's a good point, for... settings in a future development could be implemented.

Please, if you want to put here feature requests, put it in the title, because an issue is a problem and a petition is a feature request. 

Thanks for your comments.

**Comment by xmha97** [comment]
Ok, thanks.

**Comment by bitstuffing** [comment]
I've closed a little issue with refresh layout, so I can implement it now. 

I'm not a UX designer but... I will try to do it, in the next commits you should be able to see this functionality (change layout from light to dark by user choose in settings)

EDIT: By the moment, at the current commit you're able to see in dark mode if your system is in dark mode. I will investigate how to force a theme and include it in the settings part.

**Comment by bitstuffing** [comment]
Finished featured requested, added to last commit.
