### ISSUE TITLE
Add pages later

### ISSUE THREAD

**Issue by xmha97** [bitstuffing/campdf#3]
Can I add some pages later? (Like CamScanner)

**Comment by bitstuffing** [comment]
Sorry, I don't use CamScanner since some years, are you asking about a PDF editor?

It could be a feature request, but... I think it could be some heavy changes to get this future feature

**Comment by xmha97** [comment]
> are you asking about a PDF editor?

Yes



> I think it could be some heavy changes to get this future feature

Ok, If adding this feature is taking too long, please close this issue.
